"""
Centralizes all configuration constants for this project.
"""

# --- 일반 설정 ---
COL_ACCESS_TIME = "접속일시"
COL_ALT_ACCESS_TIME_1 = "접근일시"
COL_ALT_ACCESS_TIME_2 = "일시"
COL_EMPLOYEE_ID = "교직원ID"
EXCEL_EXTENSIONS = (".xlsx", ".xls")
SHEET_NAME_MAX_CHARS = 31

# --- 로그인 검사기 (login_checker.py) ---
LOGIN_LOG_FILE_PREFIX = "사용자접속내역_Login내역_"
LOGIN_CHECK_REPORT_BASE = "[붙임2] 코러스 사용자 접근 기록"
LOGIN_REPORT_IP_SWITCH_SUFFIX = "60분IP"
LOGIN_REPORT_OFF_HOURS_SUFFIX = "업무시간외"
LOGIN_REPORT_HOLIDAY_SUFFIX = "휴일"
COL_IP = "IP"
LOGIN_IP_SWITCH_WINDOW_HOURS = 1
LOGIN_IP_SWITCH_MIN_IPS = 3
LOGIN_OFF_HOURS_START = 23
LOGIN_OFF_HOURS_END = 7
LOGIN_IP_FAST_SWITCH_MINUTES = 5
COL_ESTIMATED_REASON = "사유추정"
REASON_SAME_SUBNET = "동일 네트워크 내 PC 변경"
REASON_CAMPUS_MOVE = "캠퍼스 내 이동 추정"
REASON_EXTERNAL_NETWORK = "외부 네트워크 접속 포함"
REASON_FAST_SWITCH_SUFFIX = "(빠른 전환)"
# Refined reason strings (replaces REASON_EXTERNAL_NETWORK for different /16 cases)
REASON_PRIVATE_CROSS_SUBNET = "사설 네트워크 간 이동"
REASON_PRIVATE_PUBLIC_MIX = "사설/공인 네트워크 혼용"
REASON_PUBLIC_CROSS_NETWORK = "공인 네트워크 간 전환"
# Risk level
COL_RISK_LEVEL = "위험도"
RISK_LOW = "낮음"
RISK_MEDIUM = "중간"
RISK_HIGH = "높음"
# Analysis metadata
COL_UNIQUE_IP_COUNT = "고유IP수"
COL_UNIQUE_SUBNET_COUNT = "고유서브넷수"

# --- 개인정보 파일 접근 검사기 (personal_file_checker.py) ---
PERSONAL_INFO_ACCESS_LOG_PREFIX = "개인정보 접속기록 조회_"
PERSONAL_INFO_REPORT_BASE = "[붙임3] 개인정보 접속 기록"
MERGED_PERSONAL_INFO_ACCESS_FILENAME_TEMPLATE = "[붙임3] 개인정보 접속 기록_{}.xlsx"
PERSONAL_INFO_ACCESS_MASTER_SUFFIX = "인사마스터"
PERSONAL_INFO_ACCESS_HIGH_VOLUME_VIEWS_SUFFIX = "1000건이상조회"
PERSONAL_INFO_ACCESS_HIGH_VOLUME_SAVES_SUFFIX = "100건이상저장"
COL_PROGRAM_NAME = "프로그램명"
COL_DETAIL_CONTENT = "상세내용"
COL_JOB_PERFORMANCE = "수행업무"
COL_EMPLOYEE_NAME = "성명"
VIEW_THRESHOLD = 1000
SAVE_THRESHOLD = 100

# --- 다운로드 사유 검사기 (download_reason_checker.py) ---
PERSONAL_INFO_DOWNLOAD_REASON_PREFIX = "개인정보 다운로드 사유 조회_"
DOWNLOAD_REASON_REPORT_BASE = "[붙임4] 개인정보 다운로드 사유"
DOWNLOAD_REASON_INVALID_REASON_SUFFIX = "사유이상"
DOWNLOAD_REASON_HIGH_DOWNLOAD_COUNT_SUFFIX = "100건 초과"
DOWNLOAD_REASON_HIGH_FREQUENCY_SUFFIX = "1시간20건초과"
DOWNLOAD_REASON_OFF_HOURS_SUFFIX = "업무시간외"
COL_DOWNLOAD_REASON = "다운로드사유"
COL_DOWNLOAD_COUNT = "다운로드데이터수(건)"
DOWNLOAD_COUNT_THRESHOLD = 100
DOWNLOAD_FREQUENCY_THRESHOLD = 20
DOWNLOAD_OFF_HOURS_START = 23
DOWNLOAD_OFF_HOURS_END = 8
CROSS_REF_TIME_WINDOW_MINUTES = 5
CROSS_REF_WINDOW_STEPS = [5, 10, 15]
COL_ACCESS_LOG_SUMMARY = "접속기록요약"

# --- 권한 부여 검사기 (ncmarm001_checker.py) ---
NCMARM001_FILE_PREFIX = "NCMARM001_"
NCMARM001_REPORT_BASE = "[붙임5] 권한 부여 기록"
NCMARM001_UNAUTHORIZED_GRANT_SUFFIX = "승인없는권한상승"
COL_REGISTRANT_ID = "등록자신분번호"

# --- ZIP 파일 설정 ---
# ZIP 파일 생성 시 사용할 prefix와 파일명 매핑
ZIP_FILE_PREFIXES = [
    LOGIN_CHECK_REPORT_BASE,
    PERSONAL_INFO_REPORT_BASE,
    DOWNLOAD_REASON_REPORT_BASE,
    NCMARM001_REPORT_BASE,
]

# --- HWPX 보고서 생성 (report_generator.py) ---
HWPX_REPORT_BASE = "[붙임1] 코러스 개인정보처리시스템 접속기록 점검 대장"
